# Generated by Django 5.0.8 on 2024-08-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Model'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of User'),
        ),
    ]
