# Generated by Django 5.0.8 on 2024-10-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_model_name_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guid',
            field=models.UUIDField(default='1ef504d9-4c29-4502-a815-7880df05cf41', editable=False),
            preserve_default=False,
        ),
    ]
