# Generated by Django 5.0.8 on 2024-10-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('go_to_service', 'Go to service')], default='processing', max_length=50),
        ),
    ]
