# Generated by Django 5.0.8 on 2025-02-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_guid_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_guid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
