# Generated by Django 5.0.8 on 2025-02-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_driver_guid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
