# Generated by Django 5.0.8 on 2024-08-29 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trajectories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluetoothCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluetooth', to='trajectories.vehicle')),
            ],
        ),
    ]
