# Generated by Django 5.0.8 on 2025-02-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluetooth', '0002_userbluetoothcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BluetoothCount',
        ),
    ]
