# Generated by Django 5.0.8 on 2025-09-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_patient_age_patient_first_name_patient_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
    ]
