# Generated by Django 5.0.8 on 2025-09-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_patient_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=400, null=True)),
                ('treatment_service', models.CharField(blank=True, choices=[('general_medicine', 'General Medicine'), ('pediatrics', 'Pediatrics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('gynecology', 'Gynecology'), ('ophthalmology', 'Ophthalmology'), ('dentistry', 'Dentistry'), ('psychiatry', 'Psychiatry')], null=True)),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='in_process', null=True, verbose_name=[('accepted', 'Accepted'), ('rejeceted', 'Rejected'), ('in_process', 'In_process')])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'time')},
        ),
    ]
