# Generated by Django 5.0.8 on 2025-09-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_visitorappointment_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='user_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
